jenkins:
  systemMessage: "Jenkins configured automatically by JCasC"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: "admin"
         password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('Deploy-App') {
        definition {
          cps {
            sandbox(true)
            script('''
              pipeline {
                agent any
                stages {
                  stage('Deploy') {
                    steps {
                      dir('/home/a.lopez.g/Documents/trabajos/jenkins_container/003_app') {
                        sh 'docker compose --env-file ../env.development -p 003_app up -d --build'
                        sh 'docker compose --env-file ../env.development -p 003_app ps'
                      }
                    }
                  }
                }
              }
            ''')
          }
        }
      }
  - script: >
      pipelineJob('Stop-App') {
        definition {
          cps {
            sandbox(true)
            script('''
              pipeline {
                agent any
                stages {
                  stage('Stop') {
                    steps {
                      dir('/home/a.lopez.g/Documents/trabajos/jenkins_container/003_app') {
                        sh 'docker compose --env-file ../env.development -p 003_app down'
                      }
                    }
                  }
                }
              }
            ''')
          }
        }
      }
  - script: >
      pipelineJob('Deploy-Infrastructure') {
        parameters {
          choiceParam('ACTION', ['plan', 'apply', 'destroy'], 'Terraform action to perform')
          booleanParam('CONFIRM', false, 'Confirm execution (required for apply/destroy)')
        }
        definition {
          cps {
            sandbox(true)
            script('''
              pipeline {
                agent any
                environment {
                  HCLOUD_TOKEN = credentials('hcloud-token')
                }
                stages {
                  stage('Init') {
                    steps {
                      withCredentials([sshUserPrivateKey(credentialsId: 'ssh-credentials', keyFileVariable: 'SSH_KEY_FILE')]) {
                        dir('/home/a.lopez.g/Documents/trabajos/jenkins_container/002_terraform') {
                          script {
                            env.PUBLIC_KEY = sh(script: 'ssh-keygen -y -f $SSH_KEY_FILE', returnStdout: true).trim()
                            sh """
                              set -a
                              . ../env.development
                              set +a
                              terraform init
                            """
                          }
                        }
                      }
                    }
                  }
                  stage('Action') {
                    steps {
                      withCredentials([sshUserPrivateKey(credentialsId: 'ssh-credentials', keyFileVariable: 'SSH_KEY_FILE')]) {
                        dir('/home/a.lopez.g/Documents/trabajos/jenkins_container/002_terraform') {
                          script {
                            if (params.ACTION == 'plan') {
                              sh """
                                set -a
                                . ../env.development
                                set +a
                                terraform plan -var="hcloud_token=\$HCLOUD_TOKEN" -var="ssh_public_key=\$PUBLIC_KEY"
                              """
                            } else if (params.ACTION == 'apply') {
                              if (params.CONFIRM) {
                                sh """
                                  set -a
                                  . ../env.development
                                  set +a
                                  terraform apply -auto-approve -var="hcloud_token=\$HCLOUD_TOKEN" -var="ssh_public_key=\$PUBLIC_KEY"
                                """
                              } else {
                                error "Confirmation required for APPLY action"
                              }
                            } else if (params.ACTION == 'destroy') {
                              if (params.CONFIRM) {
                                sh """
                                  set -a
                                  . ../env.development
                                  set +a
                                  terraform destroy -auto-approve -var="hcloud_token=\$HCLOUD_TOKEN" -var="ssh_public_key=\$PUBLIC_KEY"
                                """
                              } else {
                                error "Confirmation required for DESTROY action"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            ''')
          }
        }
      }
  - script: >
      pipelineJob('Deploy-Production') {
        parameters {
          booleanParam('CONFIRM', false, 'Confirm deployment to production VPS')
        }
        definition {
          cps {
            sandbox(true)
            script('''
              pipeline {
                agent any
                environment {
                  VPS_USER = 'root'
                  VPS_PATH = '/opt/app'
                  PROJECT_DIR = '/home/a.lopez.g/Documents/trabajos/jenkins_container'
                }
                stages {
                  stage('Validate') {
                    steps {
                      script {
                        if (!params.CONFIRM) {
                          error('Deployment not confirmed. Check CONFIRM to proceed.')
                        }
                      }
                    }
                  }
                  stage('Get VPS IP') {
                    steps {
                      dir("${PROJECT_DIR}/002_terraform") {
                        script {
                          env.VPS_IP = sh(script: 'terraform output -raw server_ip', returnStdout: true).trim()
                          echo "VPS IP: ${env.VPS_IP}"
                        }
                      }
                    }
                  }
                  stage('Copy Files to VPS') {
                    steps {
                      withCredentials([sshUserPrivateKey(credentialsId: 'ssh-credentials', keyFileVariable: 'SSH_KEY')]) {
                        sh """
                          ssh -o StrictHostKeyChecking=no -i \\$SSH_KEY ${VPS_USER}@${VPS_IP} 'mkdir -p ${VPS_PATH}'
                          rsync -avz --delete -e 'ssh -o StrictHostKeyChecking=no -i '\\$SSH_KEY \\
                            ${PROJECT_DIR}/003_app/ ${VPS_USER}@${VPS_IP}:${VPS_PATH}/
                          scp -o StrictHostKeyChecking=no -i \\$SSH_KEY \\
                            ${PROJECT_DIR}/env.production ${VPS_USER}@${VPS_IP}:${VPS_PATH}/.env
                        """
                      }
                    }
                  }
                  stage('Deploy on VPS') {
                    steps {
                      withCredentials([
                        sshUserPrivateKey(credentialsId: 'ssh-credentials', keyFileVariable: 'SSH_KEY'),
                        string(credentialsId: 'hetzner-dns-token', variable: 'DNS_TOKEN')
                      ]) {
                        sh """
                          ssh -o StrictHostKeyChecking=no -i \\$SSH_KEY ${VPS_USER}@${VPS_IP} '
                            cd ${VPS_PATH}
                            export HETZNER_DNS_TOKEN=${DNS_TOKEN}
                            docker compose --env-file .env --profile production up -d --build
                            docker compose --env-file .env ps
                          '
                        """
                      }
                    }
                  }
                }
                post {
                  success {
                    echo "Deployed successfully to https://tonilogar.com"
                  }
                }
              }
            ''')
          }
        }
      }
